server:
  port: 9095

spring:
  application:
    name: ms-gateway-server

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: ms-participants-service
          uri: lb://ms-participants-service
          predicates:
            - Path=/participants/**, /registrations/**
          filters:
            - name: AuthFilter
        - id: ms-events-service
          uri: lb://ms-events-service
          predicates:
            - Path=/events/**, /sessions/**
          filters:
            - name: AuthFilter
        - id: ms-auth-service
          uri: lb://ms-auth-service
          predicates:
            - Path=/auth/**
          filters: []

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8095/eureka}
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
