server:
  port: 9095

spring:
  application:
    name: ms-gateway-server

  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:4200"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedCredentials: true
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      routes:
        - id: ms-auth-service
          uri: lb://ms-auth-service
          predicates:
            - Path=/auth/**

        - id: mse-attendance
          uri: lb://mse-attendance
          predicates:
            - Path=/attendances/**

        - id: mse-notification
          uri: lb://mse-notification
          predicates:
            - Path=/notifications/**, /notification-templates/**

        - id: mse-report
          uri: lb://mse-report
          predicates:
            - Path=/reports/**, /report-logs/**

        - id: ms-participants-service
          uri: lb://ms-participants-service
          predicates:
            - Path=/participants/**
          filters:
            - name: AuthFilter
        - id: ms-events-service
          uri: lb://ms-events-service
          predicates:
            - Path=/events/**, /sessions/**
          filters:
            - name: AuthFilter
        - id: ms-registration-service
          uri: lb://ms-registration-service
          predicates:
            - Path=/registrations/**
          filters:
            - name: AuthFilter
        - id: ms-payment-service
          uri: lb://ms-payment-service
          predicates:
            - Path=/payment-orders/**
          filters:
            - name: AuthFilter



eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8095/eureka}
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
