spring:
  application:
    name: mse-notification


  datasource:
    url: jdbc:mysql://localhost:3306/mse_notification?useSSL=false&serverTimezone=UTC
    username: root
    password: topgym123
    driver-class-name: com.mysql.cj.jdbc.Driver


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect


server:
  port: 8082


# Swagger OpenAPI
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /doc/swagger-ui.html


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8095/eureka
  instance:
    hostname: localhost